const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api', require('./auth'));
app.use('/api/movies', require('./movies'));
app.use('/api/shows', require('./shows'));
app.use('/api/bookings', require('./bookings'));
app.listen(5000, () => console.log("Server running on http://localhost:5000"));
